name: Python Multi-OS Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}  # Matrix strategy picks OS
    strategy:
      matrix:
         include:
            - os: ubuntu-latest
              python-version: "2.7"
            - os: ubuntu-latest
              python-version: "3.13"
            - os: windows-latest
              python-version: "3.13"
            - os: macos-latest
              python-version: "3.13"
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run Tests
        run: |
          python -m unittest discover -s tests