name: Python Multi-OS Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true  # Ignore if no requirements.txt exists

      - name: Run Tests
        id: run_tests
        run: |
          python -m unittest discover -s tests
        continue-on-error: false  # Stop on failure

      - name: Store Test Results
        if: always()
        run: echo "TESTS_PASSED=${{ job.status }}" >> $GITHUB_ENV
